#!/usr/bin/bash
kkae_version='v1.0'

debug_message () {
if [[ ${debug} == 'true' ]] ; then
  echo "${@}"
fi
}

# Determine the display server used
if [[ "${XDG_SESSION_TYPE}" == "wayland" ]] ; then
  clipboard_manager='wl-copy'
elif [[ "${XDG_SESSION_TYPE}" == "x11" ]] ; then
  clipboard_manager='xclip'
fi

# Make sure all dependencies are met
for dependency in tr fold sort head cat ${clipboard_manager} ; do
  if ! which ${dependency} &> /dev/null ; then
    printf "Missing dependency: %s.\n" "${dependency}" >&2
    exit 1
  fi
done

usage() {
cat << EOF
usage: ${0} [-asmdpwbvh] [-l LENGTH] [-c CASE] [-e LIST]
Generate a random password and save it into the clipboard.
  -l LENGTH  Character length of the password (default is ${password_length}).
  -c CASE    Only include lowercase or uppercase letters.
  -a         Only include alphanumerical characters.
  -s         Include normally ignored similar characters (${similar_characters}).
  -e 'LIST'  String (in single quotes) or file with excluded characters.
  -m         Save the password into the middle-click clipboard.
  -d         Do not send a notification when the password has been saved.
  -p         Print the password instead of saving it into the clipboard.
  -w         Print the list of currently included characters and exit.
  -b         Enable debug mode.
  -v         Print the version number and exit.
  -h         Print these instructions and exit.
EOF
}

password_length='16'
maximum_password_length='256'
password_case='both' # valid values: lowercase, uppercase, both
tr_character_set='[:graph:]' # man tr to see available options
similar_characters="0oO1lI\"'"
excluded_characters=''
middle_click_clipboard='false'
do_not_notify='false'
countdown='5' # waiting time in seconds for a valid password before giving up
debug='false'
# If /etc/kkae.conf exists, overwrite the variables
if [[ -f /etc/kkae.conf ]] ; then
  source /etc/kkae.conf
fi

# Parse the command-line options
while getopts l:c:ase:mdpwbvh option ; do
  case ${option} in
    l) password_length=${OPTARG}
       valid_number='^[0-9]+$'
       if ! [[ ${password_length} =~ ${valid_number} ]] ||\
       [[ ${password_length} -lt 0 ]] ||\
       [[ ${password_length} -gt ${maximum_password_length} ]]
       then
         printf "Option -l requires a number between 0 and %s.\n" "${maximum_password_length}">&2
         printf "Edit /etc/kkae.conf to change the maximum password length.\n" >&2
         exit 1
       fi ;;
    c) password_case=${OPTARG}
       if [[ ${password_case} == 'lowercase' ]] ; then
         excluded_letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
       elif [[ ${password_case} == 'uppercase' ]] ; then
         excluded_letters='abcdefghijklmnopqrstuvwxyz'
       else
         printf "Option -c accepts the following paramaters: lowercase, uppercase.\n" >&2
         exit 1
       fi
       ;;
    a) tr_character_set='[:alnum:]' ;;
    s) similar_characters='' ;;
    e) if [[ -f ${OPTARG} ]] ; then
         excluded_characters=$(cat "${OPTARG}")
         if [[ $(wc -l "${excluded_characters}") -gt 1 ]] ; then
           printf "The exclusion list must be a single line.\n" >&2
           exit 1
         fi
       else
         excluded_characters="${OPTARG}"
       fi
       ;;
    m) middle_click_clipboard='true' ;;
    d) do_not_notify='true' ;;
    p) print_password='true' ;;
    w) which_characters='true' ;;
    b) debug='true' ;;
    v) printf "%s\n" "${kkae_version}" && exit 0 ;;
    h) usage && exit 0 ;;
    *) usage && exit 1 ;;
  esac
done

# Clear the options parsed by getopts
shift $(( ${OPTIND} - 1 ))

# Exit in case an invalid option has been entered
if [[ ${#} -gt 0 ]] ; then
  printf "Invalid option or parameter.\n" >&2
  usage
  exit 1
fi

debug_message "Display server detected: ${XDG_SESSION_TYPE}"

valid_characters=$(tr -dc "${tr_character_set}" < /dev/urandom |\
tr -d "${excluded_characters}${similar_characters}${excluded_letters}" |\
head -c 10000 | fold -w1 | sort -u | tr -d '\n')
debug_message "Valid characters: ${valid_characters}"
valid_special_characters=$(echo "${valid_characters}" | tr -d '[:alnum:]' |\
head -c 10000 | fold -w1 | sort -u | tr -d '\n')
debug_message "Valid special characters: ${valid_special_characters}"

if [[ ${which_characters} = 'true' ]] ; then
  echo "${valid_characters}"
  exit 0
fi

generate_password () {
  password=$(tr -dc "${tr_character_set}" < /dev/urandom |\
  tr -d "${excluded_characters}${similar_characters}${excluded_letters}" |\
  head -c "${password_length}")
}

debug_message "Preparing to generate the password…"
# Pass a non-zero diversity target to trigger the while loop
password_diversity_target='1'
# Generate passwords until at least one character of each selected category is found in a single password
while [[ ${password_diversity} -ne ${password_diversity_target} ]] ; do
  timeout () {
    printf "Could not generate a valid password after %ss.\n" "${countdown}" >&2
    printf "Try again, or review your parameters.\n" >&2
    printf "Edit /etc/kkae.conf to increase the timeout.\n" >&2
    if [[ ${do_not_notify} == 'false' ]] ; then
      notify-send -t 1000 -i dialog-password-symbolic kkae "Could not generate a valid password in time." ||\
      osascript -e 'display notification "Could not generate a password in time" with title "kkae"'
    fi
    exit 2
  }
  # Quit the program if a valid password could not be generated before the ${countdown}
  (( ${SECONDS} < ${countdown} )) || timeout
  generate_password
  # Reset the password diversity target on each new pass
  password_diversity_target='0'
  # Check if the password should contain at least one character of a given category
  if [[ "${valid_characters}" == *[0-9]* ]] ; then
    password_diversity_target=$(( ${password_diversity_target} + 1 ))
  fi
  if [[ "${valid_characters}" == *[a-z]* ]] ; then
    password_diversity_target=$(( ${password_diversity_target} + 1 ))
  fi
  if [[ "${valid_characters}" == *[A-Z]* ]] ; then
    password_diversity_target=$(( ${password_diversity_target} + 1 ))
  fi
  if [[ "${#valid_special_characters}" -gt 0 ]] ; then
    password_diversity_target=$(( ${password_diversity_target} + 1 ))
  fi

  # Reset the password diversity on each new pass
  password_diversity='0'
  # Create a function to record the diversity of the generated password
  record_diversity () {
  password_diversity=$(( ${password_diversity} + 1 ))
  }
  # Check if the password contains at least one number of a given category
  if [[ "${password}" == *[0-9]* ]] ; then
    record_diversity
  fi
  if [[ "${password}" == *[a-z]* ]] ; then
    record_diversity
  fi
  if [[ "${password}" == *[A-Z]* ]] ; then
    record_diversity
  fi
  special_characters_in_password=$(echo "${password}" | tr -d '[a-zA-Z0-9]\n')
  if [[ "${#special_characters_in_password}" -gt 0 ]] ; then
    record_diversity
  fi
done
debug_message "Password generated: ${password}"

if [[ ${print_password} = 'true' ]] ; then
  echo "${password}"
  debug_message "Printing password:"
  exit 0
fi

# Save the password to the clipboard
case ${XDG_SESSION_TYPE} in
  wayland)  if [[ ${middle_click_clipboard} = 'true' ]] ; then
              debug_message "Saving the password into the middle-click clipboard."
              selection='--primary'
            fi
              printf "%s" "${password}" | wl-copy ${selection}
              debug_message "Password copied into the Wayland clipboard." ;;
  x11)      if [[ ${middle_click_clipboard} = 'true' ]] ; then
              debug_message "Saving the password into the middle-click clipboard."
              selection='primary'
            else
              selection='clipboard'
            fi
            printf "%s" "${password}" | xclip -selection ${selection}
            debug_message "Password copied into the X11 clipboard." ;;
  *)        if [[ $(uname) == 'Darwin' ]] ; then
              platform='macos'
              debug_message "System detected: macOS"
              if [[ ${middle_click_clipboard} = 'true' ]] ; then
                printf "Error: middle-click clipboard not available in macOS.\n" >&2
                exit 1
              fi
              printf "%s" "${password}" | pbcopy
              debug_message "Password copied into the macOS clipboard."
            else
              platform='windows'
              debug_message "System detected: Windows Subsystem for Linux"
              if [[ ${middle_click_clipboard} = 'true' ]] ; then
                printf "Error: middle-click clipboard not available in WSL.\n" >&2
                exit 1
              fi
              printf "%s" "${password}" | clip.exe
              debug_message "Password copied into the Windows clipboard."
            fi ;;
esac

if [[ ${do_not_notify} == 'true' ]] ; then
  debug_message "Do not send a notification."
  exit 0
else
  if [[ ${platform} == 'macos' ]] ; then
    osascript -e 'display notification "New random password saved in the clipboard." with title "kkae"'
    debug_message "Notification sent. Exit code: ${?}"
  elif [[ ${platform} == 'windows' ]] ; then
    notify-send() { wsl-notify-send.exe --category $WSL_DISTRO_NAME "${@}"; }
    notify-send --category kkae --appId kkae "New random password saved in the clipboard."
    debug_message "Notification sent. Exit code: ${?}"
  else
    notify-send -t 1000 -i dialog-password-symbolic kkae "New random password saved in the clipboard."
    debug_message "Notification sent. Exit code: ${?}"
  fi
  exit 0
fi
